In [1]:
import numpy as np

In [2]:
# Tableau d'entiers:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# Une liste de listes est transformée en un tableau multi-dimensionnel
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)

# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)

# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

# Celle-ci vous la conaissez déjà! Essayez aussi "randint" et "normal"
np.random.random((3, 3))

# La matrice identité de taille 3x3 
# (matrice identité : https://fr.wikipedia.org/wiki/Matrice_identit%C3%A9)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int64


In [8]:
x1 = np.array([range(i, i+5) for i in [2,4,6]])
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  2
forme de x1:  (3, 5)
taille de x1:  15
type de x1:  int64


In [9]:
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1

print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

[3 5 2 4 7 6]
3
6
8
[   3 1000    2    4    7    6]
[3 3 2 4 7 6]


In [10]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[3 3 2 4 7]
[6]
[3 2 7]


In [11]:
x1[::-1]

array([6, 7, 4, 2, 3, 3])

In [12]:
print(x2)

x2[0,:] # La première ligne

[[8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]


array([8, 8, 1, 6])

In [13]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [14]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [15]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

[0.2        0.25       1.         0.25       0.16666667]
1.42 s ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
%timeit (1.0 / tableau_large)

1.09 ms ± 34.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [18]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [19]:
x = np.random.rand(3,3)
print(x)
x > 0.5

[[0.703217   0.18815616 0.84843905]
 [0.90182436 0.51108795 0.39700962]
 [0.55506003 0.21672088 0.51626383]]


array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [22]:
np.where(x > 0.5)

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 1, 0, 2]))

In [23]:
L = np.random.random(100)
np.sum(L)

49.39274697492188

In [24]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

61.7 ms ± 311 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
507 µs ± 9.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.08782143 0.15618846 0.73099033 0.6427996 ]
 [0.09425156 0.1035502  0.32354189 0.3706353 ]
 [0.87966194 0.44429964 0.67253984 0.93091273]]
La somme de tous les éléments de M:  5.437192908814353
Les sommes des colonnes de M:  [1.06173492 0.7040383  1.72707205 1.94434763]


In [26]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [27]:
a + 5

array([5, 6, 7])

In [28]:
M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+a vaut: \n", M+a)

M vaut: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+a vaut: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [29]:
a = np.arange(3)
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])