In [1]:
import numpy as np
un_panda_numpy = np.array([100,5,20,80])
un_panda_numpy

array([100,   5,  20,  80])

In [2]:
famille_panda = [
    np.array([100, 5  , 20, 80]), # maman panda
    np.array([50 , 2.5, 10, 40]), # bébé panda
    np.array([110, 6  , 22, 80]), # papa panda
]

In [3]:
famille_panda = [
    [100, 5  , 20, 80], # maman panda
    [50 , 2.5, 10, 40], # bébé panda
    [110, 6  , 22, 80], # papa panda
]
famille_panda_numpy = np.array(famille_panda)
famille_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [4]:
famille_panda_numpy[2, 0] # taille des pattes de papa panda, à la manière numpy

110.0

In [5]:
famille_panda_numpy[:, 0]

array([100.,  50., 110.])

In [6]:
import pandas as pd
famille_panda_df = pd.DataFrame(famille_panda)
famille_panda_df

0    1   2   3
0  100  5.0  20  80
1   50  2.5  10  40
2  110  6.0  22  80

In [7]:
famille_panda_df = pd.DataFrame(famille_panda_numpy,
                                index = ['maman', 'bebe', 'papa'],
                                columns = ['pattes', 'poil', 'queue', 'ventre'])
famille_panda_df

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0

In [8]:
famille_panda_df.ventre
famille_panda_df["ventre"]

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [9]:
for ind_ligne, contenu_ligne in famille_panda_df.iterrows():
    print("Voici le panda %s :" % ind_ligne)
    print(contenu_ligne)
    print("--------------------")

Voici le panda maman :
pattes    100.0
poil        5.0
queue      20.0
ventre     80.0
Name: maman, dtype: float64
--------------------
Voici le panda bebe :
pattes    50.0
poil       2.5
queue     10.0
ventre    40.0
Name: bebe, dtype: float64
--------------------
Voici le panda papa :
pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
--------------------


In [10]:
famille_panda_df.iloc[2] # Avec iloc(), indexation positionnelle
famille_panda_df.loc["papa"] # Avec loc(), indexation par label

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [11]:
famille_panda_df["ventre"] == 80

maman     True
bebe     False
papa      True
Name: ventre, dtype: bool

In [12]:
masque = famille_panda_df["ventre"] == 80
pandas_80 = famille_panda_df[masque]

# On écrit plus souvent cela de cette manière :
# pandas_80 = famille_panda_df[famille_panda_df["ventre"] == 80]

pandas_80

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
papa    110.0   6.0   22.0    80.0

In [13]:
famille_panda_df[~masque]

pattes  poil  queue  ventre
bebe    50.0   2.5   10.0    40.0

In [14]:
quelques_pandas = pd.DataFrame([[105,4,19,80],[100,5,20,80]],      # deux nouveaux pandas
                               columns = famille_panda_df.columns) 
                               # même colonnes que famille_panda_df
tous_les_pandas = famille_panda_df.append(quelques_pandas)
tous_les_pandas

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0
1       100.0   5.0   20.0    80.0

In [15]:
tous_les_pandas.drop_duplicates()

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0

In [18]:
# accéder aux noms des colonnes
famille_panda_df.columns

# créer une nouvelle colonne, composée de chaînes de caractères
famille_panda_df["sexe"] = ["f", "f", "m"] 
# la maman et le bébé sont des femelles, le papa est un mâle

# obtenir le nombre de lignes
len(famille_panda_df)

3

In [19]:
# obtenir les valeurs distinctes d'une colonne :
# pour la colonne ventre, il y a deux valeurs distinctes : 40 et 80
famille_panda_df.ventre.unique()

array([80., 40.])

In [21]:
#data = pd.read_csv("data.csv", sep=";")